# Centralized Configuration for Cloud Gateway
# This file is served by Config Server to Gateway Service

server:
  port: 8080  # Gateway port (main entry point)

spring:
  # Gateway Routing Configuration
  cloud:
    gateway:
      routes:
        # Order Service Route
        - id: order-service
          uri: lb://order-service  # Load-balanced routing
          predicates:
            - Path=/order/**  # Route pattern
        # Payment Service Route
        - id: payment-service
          uri: lb://payment-service  # Load-balanced routing
          predicates:
            - Path=/payment/**  # Route pattern

# Service Discovery Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Monitoring and Tracing Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for learning
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"