server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/paymentdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

# Payment Processing Configuration
payment:
  processing:
    timeout: 30s
    retry-attempts: 3
